branch-defaults:
  main:
    environment: null
deploy:
  artifact: target/math-pyramid-0.0.2-SNAPSHOT.jar
global:
  application_name: math-pyramid
  branch: null
  default_ec2_keyname: null
  default_platform: Corretto 17 running on 64bit Amazon Linux 2023
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
